# Generated by Django 6.0 on 2026-02-11 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(db_index=True, max_length=10)),
                ('year', models.IntegerField(db_index=True)),
                ('broad_discipline', models.CharField(max_length=200)),
                ('college_school', models.CharField(max_length=200)),
                ('major_name', models.CharField(db_index=True, max_length=200)),
                ('applicants', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('admits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('enrolls', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('admit_gpa_min', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('admit_gpa_max', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('enroll_gpa_min', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('enroll_gpa_max', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('admit_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('yield_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Transfer Data',
                'verbose_name_plural': 'Transfer Data',
                'ordering': ['-year', 'university', 'major_name'],
                'indexes': [models.Index(fields=['university', 'year'], name='api_transfe_univers_0539ed_idx'), models.Index(fields=['year', 'major_name'], name='api_transfe_year_e6277a_idx'), models.Index(fields=['broad_discipline'], name='api_transfe_broad_d_7279d9_idx'), models.Index(fields=['university', 'year', 'major_name'], name='api_transfe_univers_00a56c_idx')],
                'unique_together': {('university', 'year', 'major_name', 'college_school')},
            },
        ),
    ]
