# Generated by Django 6.0 on 2025-12-30 04:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Academic year in format YYYY-YY (e.g., 2023-24)', max_length=9, unique=True)),
                ('start_year', models.IntegerField(help_text='Starting year (e.g., 2023)')),
                ('end_year', models.IntegerField(help_text='Ending year (e.g., 2024)')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_year'],
                'indexes': [models.Index(fields=['start_year'], name='api_academi_start_y_242aae_idx'), models.Index(fields=['year'], name='api_academi_year_9cdfc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunityCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(default='CA', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community College',
                'verbose_name_plural': 'Community Colleges',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_communi_name_6584ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Major name (e.g., Computer Science)', max_length=200)),
                ('broad_discipline', models.CharField(db_index=True, help_text='Broad discipline category (e.g., Engineering)', max_length=200)),
                ('college_school', models.CharField(blank=True, help_text='College or school within UC campus', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
                'ordering': ['broad_discipline', 'name'],
                'indexes': [models.Index(fields=['name'], name='api_major_name_ec6ab8_idx'), models.Index(fields=['broad_discipline'], name='api_major_broad_d_dc911b_idx'), models.Index(fields=['name', 'broad_discipline'], name='api_major_name_7a8d13_idx')],
                'unique_together': {('name', 'broad_discipline')},
            },
        ),
        migrations.CreateModel(
            name='UCCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Campus code (e.g., UCB, UCLA)', max_length=10, unique=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UC Campus',
                'verbose_name_plural': 'UC Campuses',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='api_uccampu_code_3761ef_idx'), models.Index(fields=['name'], name='api_uccampu_name_031e98_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransferData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants', models.IntegerField(blank=True, help_text='Number of applicants', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('admits', models.IntegerField(blank=True, help_text='Number of admitted students', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('enrolls', models.IntegerField(blank=True, help_text='Number of enrolled students', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('acceptance_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Acceptance rate as percentage (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('average_gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Average GPA of admitted students', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4.0)])),
                ('gpa_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum GPA in range', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4.0)])),
                ('gpa_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum GPA in range', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4.0)])),
                ('yield_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Yield rate as percentage (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_data', to='api.academicyear')),
                ('community_college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_data', to='api.communitycollege')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_data', to='api.major')),
                ('uc_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_data', to='api.uccampus')),
            ],
            options={
                'verbose_name': 'Transfer Data',
                'verbose_name_plural': 'Transfer Data',
                'ordering': ['-academic_year__start_year', 'uc_campus', 'major'],
                'indexes': [models.Index(fields=['academic_year', 'uc_campus'], name='api_transfe_academi_f08d33_idx'), models.Index(fields=['academic_year', 'major'], name='api_transfe_academi_98d1ef_idx'), models.Index(fields=['uc_campus', 'major'], name='api_transfe_uc_camp_3e0c89_idx'), models.Index(fields=['community_college', 'uc_campus'], name='api_transfe_communi_a2b1b6_idx'), models.Index(fields=['acceptance_rate'], name='api_transfe_accepta_b1cbed_idx'), models.Index(fields=['average_gpa'], name='api_transfe_average_5127ed_idx'), models.Index(fields=['gpa_min', 'gpa_max'], name='api_transfe_gpa_min_000045_idx'), models.Index(fields=['academic_year', 'uc_campus', 'major'], name='api_transfe_academi_e9bb57_idx')],
                'unique_together': {('academic_year', 'community_college', 'uc_campus', 'major')},
            },
        ),
    ]
