# Generated by Django 5.2.11 on 2026-02-19 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdata',
            name='broad_discipline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferdata',
            name='college_school',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferdata',
            name='major_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CampusStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(db_index=True, max_length=10)),
                ('year', models.IntegerField(db_index=True)),
                ('applicants', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('admits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('enrolls', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('admit_gpa_min', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('admit_gpa_max', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('enroll_gpa_min', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('enroll_gpa_max', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('admit_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('yield_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Campus Stats',
                'verbose_name_plural': 'Campus Stats',
                'ordering': ['-year', 'campus'],
                'unique_together': {('campus', 'year')},
            },
        ),
    ]
